namespace Game
{
    public enum LocationEnum
    {
        HerobrineHome,
        World,
        Prison,
        RoomDeveloper,
        TrueSecret,
        Cafe,
        HerobrineLaboratory,
        HerobrineLaboratoryArena,
        TrueSecretStatue,
        WismanRoom,
        OfficeRoof,
        Museum,
        MuseumBasement,
        MuseumSecret,
        Office,
        Nether,
        NetherHouse,
        NetherHouseSecret,
        ErrorWorld,
        ErrorPrison,
        ErrorCafe,
        ErrorHerobrineHome,
        ErrorMuseum,
        PalesosWorld,
        LawnPortal,
        Lawn,
    }
}